import login
import project_manage
import public_warning
import epidemic_management
import emergency_disposal
import data_stat
import logout

def demo_test_case(suite):
    #登录
    suite.addTest(login.登录('山东高速登录'))
    #项目管理
    suite.addTest(project_manage.项目管理("打开项目管理页面"))
    suite.addTest(project_manage.项目管理("法律法规"))
    suite.addTest(project_manage.项目管理("法律法规_亚洲pdf校验"))
    suite.addTest(project_manage.项目管理("法律法规_欧洲pdf校验"))
    suite.addTest(project_manage.项目管理("法律法规_非洲pdf校验"))
    suite.addTest(project_manage.项目管理("法律法规_南美洲pdf校验"))
    suite.addTest(project_manage.项目管理("预案管理"))
    suite.addTest(project_manage.项目管理("预案管理pdf校验"))
    suite.addTest(project_manage.项目管理("文件管理"))
    suite.addTest(project_manage.项目管理("规章制度"))
    suite.addTest(project_manage.项目管理("规章制度pdf校验"))
    suite.addTest(project_manage.项目管理("培训台账"))
    suite.addTest(project_manage.项目管理("体检报告"))
    suite.addTest(project_manage.项目管理("保险记录"))
    suite.addTest(project_manage.项目管理("评估报告"))
    suite.addTest(project_manage.项目管理("现场医疗"))
    suite.addTest(project_manage.项目管理("培训演练"))
    suite.addTest(project_manage.项目管理("安保方案"))
    suite.addTest(project_manage.项目管理("医疗转运"))
    suite.addTest(project_manage.项目管理("机构人数校验"))
    suite.addTest(project_manage.项目管理("选择其他机构进行人数校验"))
    suite.addTest(project_manage.项目管理("在某机构公司下的机构人数"))
    #舆情预警
    suite.addTest(public_warning.舆情预警("打开舆情预警页面"))
    suite.addTest(public_warning.舆情预警("更改风险预警信息功能"))
    suite.addTest(public_warning.舆情预警("风险可视化关闭功能"))
    suite.addTest(public_warning.舆情预警("最新国别风险报告弹层"))
    suite.addTest(public_warning.舆情预警("国别风险pdf显示"))
    suite.addTest(public_warning.舆情预警("最新舆情信息弹层"))
    suite.addTest(public_warning.舆情预警("舆情信息模块功能"))
    suite.addTest(public_warning.舆情预警("最新安全周报弹层"))
    suite.addTest(public_warning.舆情预警("安全周报模块功能"))
    suite.addTest(public_warning.舆情预警("最新预警信息弹层"))
    suite.addTest(public_warning.舆情预警("安全周报最新期数"))
    #疫情管理
    suite.addTest(epidemic_management.疫情管理("打开疫情管理页面"))
    suite.addTest(epidemic_management.疫情管理("驻外机构人数显示"))
    suite.addTest(epidemic_management.疫情管理("境外项目数显示"))
    suite.addTest(epidemic_management.疫情管理("中方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("外方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("总员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("海外疫情动态显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层每日汇总表展示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层周变化表展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层列表显示"))
    #应急处置
    suite.addTest(emergency_disposal.应急处置("打开应急处置页面"))
    suite.addTest(emergency_disposal.应急处置("打开事件上报弹层"))
    suite.addTest(emergency_disposal.应急处置("打开应急事件弹层"))
    suite.addTest(emergency_disposal.应急处置("打开值班记录弹层"))
    suite.addTest(emergency_disposal.应急处置("打开新增值班记录弹层"))
    #数据统计
    suite.addTest(data_stat.数据统计("打开数据统计页面"))
    suite.addTest(data_stat.数据统计("打开数据统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开项目管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开舆情预警统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开疫情管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开应急处置统计旁的分析报告"))
    #登出
    suite.addTest(logout.登出("登出当前账号"))

def B_and_R_test_case(suite):
    # 登录
    suite.addTest(login.登录('一带一路登录'))
    #项目管理
    suite.addTest(project_manage.一带一路项目管理("打开项目管理页面"))
    suite.addTest(project_manage.一带一路项目管理("港口介绍"))
    suite.addTest(project_manage.一带一路项目管理("历史图像"))
    suite.addTest(project_manage.一带一路项目管理("港口航线"))
    suite.addTest(project_manage.一带一路项目管理("当地法律"))
    suite.addTest(project_manage.一带一路项目管理("当地法律_亚洲pdf校验"))
    suite.addTest(project_manage.一带一路项目管理("当地法律_非洲pdf校验"))
    suite.addTest(project_manage.一带一路项目管理("当地法律_南美洲pdf校验"))
    suite.addTest(project_manage.一带一路项目管理("运载信息"))
    suite.addTest(project_manage.一带一路项目管理("评估报告"))
    #舆情预警
    suite.addTest(public_warning.舆情预警("打开舆情预警页面"))
    suite.addTest(public_warning.舆情预警("更改风险预警信息功能"))
    suite.addTest(public_warning.舆情预警("风险可视化关闭功能"))
    suite.addTest(public_warning.舆情预警("最新国别风险报告弹层"))
    suite.addTest(public_warning.一带一路舆情预警("国别风险pdf显示"))
    suite.addTest(public_warning.舆情预警("最新舆情信息弹层"))
    suite.addTest(public_warning.舆情预警("舆情信息模块功能"))
    suite.addTest(public_warning.舆情预警("最新安全周报弹层"))
    suite.addTest(public_warning.舆情预警("安全周报模块功能"))
    suite.addTest(public_warning.舆情预警("最新预警信息弹层"))
    suite.addTest(public_warning.一带一路舆情预警("安全周报最新期数"))
    #疫情管理
    suite.addTest(epidemic_management.疫情管理("打开疫情管理页面"))
    suite.addTest(epidemic_management.一带一路疫情管理("承包项目数"))
    suite.addTest(epidemic_management.一带一路疫情管理("中方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("外方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("总员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("海外疫情动态显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层每日汇总表展示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层周变化表展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层列表显示"))
    #应急处置
    suite.addTest(emergency_disposal.应急处置("打开应急处置页面"))
    suite.addTest(emergency_disposal.应急处置("打开事件上报弹层"))
    suite.addTest(emergency_disposal.应急处置("打开应急事件弹层"))
    suite.addTest(emergency_disposal.应急处置("打开值班记录弹层"))
    suite.addTest(emergency_disposal.应急处置("打开新增值班记录弹层"))
    #数据统计
    suite.addTest(data_stat.数据统计("打开数据统计页面"))
    suite.addTest(data_stat.数据统计("打开数据统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开项目管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开舆情预警统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开疫情管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开应急处置统计旁的分析报告"))
    # 登出
    suite.addTest(logout.登出("登出当前账号"))

def N_Industrial_test_case(suite):
    # 登录
    suite.addTest(login.登录('北方工业登录'))
    # 项目管理
    suite.addTest(project_manage.北方工业项目管理("打开项目管理页面"))
    suite.addTest(project_manage.北方工业项目管理("法律法规"))
    suite.addTest(project_manage.北方工业项目管理("法律法规_亚洲pdf校验"))
    suite.addTest(project_manage.北方工业项目管理("法律法规_非洲pdf校验"))
    suite.addTest(project_manage.北方工业项目管理("法律法规_南美洲pdf校验"))
    suite.addTest(project_manage.北方工业项目管理("预案管理"))
    suite.addTest(project_manage.北方工业项目管理("文件管理"))
    suite.addTest(project_manage.北方工业项目管理("规章制度"))
    suite.addTest(project_manage.北方工业项目管理("培训台账"))
    suite.addTest(project_manage.北方工业项目管理("体检报告"))
    suite.addTest(project_manage.北方工业项目管理("保险记录"))
    suite.addTest(project_manage.北方工业项目管理("评估报告"))
    suite.addTest(project_manage.北方工业项目管理("现场医疗"))
    suite.addTest(project_manage.北方工业项目管理("培训演练"))
    suite.addTest(project_manage.北方工业项目管理("安保方案"))
    suite.addTest(project_manage.北方工业项目管理("医疗转运"))
    # 舆情预警
    suite.addTest(public_warning.舆情预警("打开舆情预警页面"))
    suite.addTest(public_warning.舆情预警("更改风险预警信息功能"))
    suite.addTest(public_warning.舆情预警("风险可视化关闭功能"))
    suite.addTest(public_warning.舆情预警("最新国别风险报告弹层"))
    suite.addTest(public_warning.北方工业舆情预警("国别风险pdf显示"))
    suite.addTest(public_warning.舆情预警("最新舆情信息弹层"))
    suite.addTest(public_warning.舆情预警("舆情信息模块功能"))
    suite.addTest(public_warning.舆情预警("最新安全周报弹层"))
    suite.addTest(public_warning.舆情预警("安全周报模块功能"))
    suite.addTest(public_warning.舆情预警("最新预警信息弹层"))
    suite.addTest(public_warning.北方工业舆情预警("安全周报最新期数"))
    # 疫情管理
    suite.addTest(epidemic_management.疫情管理("打开疫情管理页面"))
    suite.addTest(epidemic_management.北方工业疫情管理("承包项目数"))
    suite.addTest(epidemic_management.北方工业疫情管理("中方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("外方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("总员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("海外疫情动态显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层每日汇总表展示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层周变化表展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层列表显示"))
    # 应急处置
    suite.addTest(emergency_disposal.应急处置("打开应急处置页面"))
    suite.addTest(emergency_disposal.应急处置("打开事件上报弹层"))
    suite.addTest(emergency_disposal.应急处置("打开应急事件弹层"))
    suite.addTest(emergency_disposal.应急处置("打开值班记录弹层"))
    suite.addTest(emergency_disposal.应急处置("打开新增值班记录弹层"))
    # 数据统计
    suite.addTest(data_stat.数据统计("打开数据统计页面"))
    suite.addTest(data_stat.数据统计("打开数据统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开项目管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开舆情预警统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开疫情管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开应急处置统计旁的分析报告"))
    # 登出
    suite.addTest(logout.登出("登出当前账号"))

#中交集团
def China_Traffic_test_case(suite):
    #登录
    suite.addTest(login.登录('中交集团登录'))
    #项目管理
    suite.addTest(project_manage.中交集团项目管理("打开项目管理页面"))
    suite.addTest(project_manage.中交集团项目管理("法律法规"))
    suite.addTest(project_manage.中交集团项目管理("法律法规_亚洲pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("法律法规_欧洲pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("法律法规_非洲pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("法律法规_南美洲pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("预案管理"))
    suite.addTest(project_manage.中交集团项目管理("预案管理pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("文件管理"))
    suite.addTest(project_manage.中交集团项目管理("规章制度"))
    suite.addTest(project_manage.中交集团项目管理("规章制度pdf校验"))
    suite.addTest(project_manage.中交集团项目管理("培训台账"))
    suite.addTest(project_manage.中交集团项目管理("体检报告"))
    suite.addTest(project_manage.中交集团项目管理("保险记录"))
    suite.addTest(project_manage.中交集团项目管理("评估报告"))
    suite.addTest(project_manage.中交集团项目管理("现场医疗"))
    suite.addTest(project_manage.中交集团项目管理("培训演练"))
    suite.addTest(project_manage.中交集团项目管理("安保方案"))
    suite.addTest(project_manage.中交集团项目管理("医疗转运"))
    suite.addTest(project_manage.中交集团项目管理("机构人数校验"))
    suite.addTest(project_manage.中交集团项目管理("选择其他机构进行人数校验"))
    suite.addTest(project_manage.中交集团项目管理("在某机构公司下的机构总数"))
    #舆情预警
    suite.addTest(public_warning.舆情预警("打开舆情预警页面"))
    suite.addTest(public_warning.舆情预警("更改风险预警信息功能"))
    suite.addTest(public_warning.舆情预警("风险可视化关闭功能"))
    suite.addTest(public_warning.舆情预警("最新国别风险报告弹层"))
    suite.addTest(public_warning.中交集团舆情信息("国别风险pdf显示"))
    suite.addTest(public_warning.舆情预警("最新舆情信息弹层"))
    suite.addTest(public_warning.舆情预警("舆情信息模块功能"))
    suite.addTest(public_warning.舆情预警("最新安全周报弹层"))
    suite.addTest(public_warning.舆情预警("安全周报模块功能"))
    suite.addTest(public_warning.舆情预警("最新预警信息弹层"))
    suite.addTest(public_warning.中交集团舆情信息("安全周报最新期数"))
    #疫情管理
    suite.addTest(epidemic_management.疫情管理("打开疫情管理页面"))
    suite.addTest(epidemic_management.中交集团疫情管理("承包项目数"))
    suite.addTest(epidemic_management.中交集团疫情管理("中方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("外方员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("总员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("海外疫情动态显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层每日汇总表展示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层周变化表展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层列表显示"))
    #应急处置
    suite.addTest(emergency_disposal.应急处置("打开应急处置页面"))
    suite.addTest(emergency_disposal.应急处置("打开事件上报弹层"))
    suite.addTest(emergency_disposal.应急处置("打开应急事件弹层"))
    suite.addTest(emergency_disposal.应急处置("打开值班记录弹层"))
    suite.addTest(emergency_disposal.应急处置("打开新增值班记录弹层"))
    #数据统计
    suite.addTest(data_stat.数据统计("打开数据统计页面"))
    suite.addTest(data_stat.数据统计("打开数据统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开项目管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开舆情预警统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开疫情管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开应急处置统计旁的分析报告"))
    #登出
    suite.addTest(logout.登出("登出当前账号"))

def T_Hrisk_test_case(suite):
    # 登录
    suite.addTest(login.登录('鼎昊国际登录'))
    # 项目管理
    suite.addTest(project_manage.鼎昊国际项目管理("打开项目管理页面"))
    suite.addTest(project_manage.鼎昊国际项目管理("法律法规"))
    suite.addTest(project_manage.鼎昊国际项目管理("法律法规_亚洲pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("法律法规_欧洲pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("法律法规_非洲pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("法律法规_南美洲pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("预案管理"))
    suite.addTest(project_manage.鼎昊国际项目管理("预案管理pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("文件管理"))
    suite.addTest(project_manage.鼎昊国际项目管理("规章制度"))
    suite.addTest(project_manage.鼎昊国际项目管理("规章制度pdf校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("培训台账"))
    suite.addTest(project_manage.鼎昊国际项目管理("体检报告"))
    suite.addTest(project_manage.鼎昊国际项目管理("保险记录"))
    suite.addTest(project_manage.鼎昊国际项目管理("评估报告"))
    suite.addTest(project_manage.鼎昊国际项目管理("现场医疗"))
    suite.addTest(project_manage.鼎昊国际项目管理("培训演练"))
    suite.addTest(project_manage.鼎昊国际项目管理("安保方案"))
    suite.addTest(project_manage.鼎昊国际项目管理("医疗转运"))
    suite.addTest(project_manage.鼎昊国际项目管理("机构人数校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("选择其他机构进行人数校验"))
    suite.addTest(project_manage.鼎昊国际项目管理("在某机构公司下的机构总数"))
    # 舆情预警
    suite.addTest(public_warning.舆情预警("打开舆情预警页面"))
    suite.addTest(public_warning.舆情预警("更改风险预警信息功能"))
    suite.addTest(public_warning.舆情预警("风险可视化关闭功能"))
    suite.addTest(public_warning.舆情预警("最新国别风险报告弹层"))
    suite.addTest(public_warning.鼎昊国际舆情信息("国别风险pdf显示"))
    suite.addTest(public_warning.舆情预警("最新舆情信息弹层"))
    suite.addTest(public_warning.舆情预警("舆情信息模块功能"))
    suite.addTest(public_warning.舆情预警("最新安全周报弹层"))
    suite.addTest(public_warning.舆情预警("安全周报模块功能"))
    suite.addTest(public_warning.舆情预警("最新预警信息弹层"))
    suite.addTest(public_warning.鼎昊国际舆情信息("安全周报最新期数"))
    # 疫情管理
    suite.addTest(epidemic_management.疫情管理("打开疫情管理页面"))
    suite.addTest(epidemic_management.鼎昊国际疫情管理("承包项目数"))
    suite.addTest(epidemic_management.鼎昊国际疫情管理("中方员工人数显示"))
    suite.addTest(epidemic_management.鼎昊国际疫情管理("外方员工人数显示"))
    suite.addTest(epidemic_management.鼎昊国际疫情管理("总员工人数显示"))
    suite.addTest(epidemic_management.疫情管理("海外疫情动态显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层显示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层每日汇总表展示"))
    suite.addTest(epidemic_management.疫情管理("境外人员情况弹层周变化表展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层展示"))
    suite.addTest(epidemic_management.疫情管理("疫情防控日报弹层列表显示"))
    # 应急处置
    suite.addTest(emergency_disposal.应急处置("打开应急处置页面"))
    suite.addTest(emergency_disposal.应急处置("打开事件上报弹层"))
    suite.addTest(emergency_disposal.应急处置("打开应急事件弹层"))
    suite.addTest(emergency_disposal.应急处置("打开值班记录弹层"))
    suite.addTest(emergency_disposal.应急处置("打开新增值班记录弹层"))
    # 数据统计
    suite.addTest(data_stat.数据统计("打开数据统计页面"))
    suite.addTest(data_stat.数据统计("打开数据统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开项目管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开舆情预警统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开疫情管理统计旁的分析报告"))
    suite.addTest(data_stat.数据统计("打开应急处置统计旁的分析报告"))
    # 登出
    suite.addTest(logout.登出("登出当前账号"))